### ISSUE TITLE
VFS: OS fs uses a reference to a file's location when calling "ChangeDir"

### ISSUE THREAD

**Issue by moezeid** [C2FO/vfs#21]
File structs in the OS fs have a member location.  File's **"Location()"** function returns the member location by simply saying _**"return file.location"**_

This becomes a problem with ChangeDir.  Say we have a file named **"foo.txt"** that has a location of _**"/home/test_files/subDir/**"_ and we want to call _**ChangeDir("relPath")**_ on that location. We would do so by saying _**"file.Location().ChangeDir("relPath")**"_ and the new location would be 
**"/home/test_files/subDir/relPath/"**.  This is an issue because the call to "Location()" returns that file's member location.  
The consequence would be that although we never moved the file, its path will have changed.  Calling _**file.Path()**_ would yield _**"home/test_files/subdir/relPath/foo.txt"**,_ which is incorrect.  
The filesystem DOES know that that location does not exist, nevertheless that is where it says the file is located.  A potential solution is returning a copy of the current location if _**"file.Location()"**_ is called

**Comment by funkyshu** [comment]
Yes, this is fixed in my EP-2432 branch.  I'll try and get that merged asap.
