### ISSUE TITLE
S3 Backend - Read() improperly reports io.EOF error after calling Seek()

### ISSUE THREAD

**Issue by seeroush** [C2FO/vfs#214]
**Describe the bug**
When reading an S3 file all the way to the end of a file (or beyond if streaming the read), and then subsequently calling Seek(0, 0) to reset the cursor to the beginning of the file, the Read() call will continue to report io.EOF errors due to an internal variable (`readEOFSeen`) not being reset by Seek().

**To Reproduce**

```go
f, _ := vfssimple.NewFile("s3://my-bucket/file.txt")

// Read byte data
firstRead, _ := io.ReadAll(f)

// Reset cursor to the beginning of the file
f.Seek(0, io.SeekStart)

// Read byte data again
secondRead, _ := io.ReadAll(f)
if len(firstRead) != len(secondRead) {
	panic(errors.New("byte data length should be the same on cursor resets")
}
```

**Expected behavior**
When resetting the cursor using `Seek()`, the data should be readable again without closing the file.

**Comment by dustin-schnee** [comment]
Issue addressed in this PR: https://github.com/C2FO/vfs/pull/215
