### ISSUE TITLE
How to set S3ForcePathStyle for AWS Client?

### ISSUE THREAD

**Issue by yellow-sky** [C2FO/vfs#96]
I'm use Minio as s3 storage. AWS Client can use it only with S3ForcePathStyle=True.
s3.Options struct does not have this parameter. Each initialization I have to create a client manually. It is very uncomfortable.
It may be possible to add this parameter to the s3.Options?

**Comment by funkyshu** [comment]
This seems pretty straightforward but it will probably be a while before I could prioritize that.  You could however in the meantime submit a patch.  Just fork `vfs`, make your changes, and do a pull request against our master branch.

**Comment by codedninja** [comment]
Made a quick patch but it's not the only thing that needs to be changed to work with Minio. Also need to implement option for disable SSE header due to Minio not having it setup by default.

https://github.com/minio/minio/issues/6367

**Comment by codedninja** [comment]
#114 Submitted the quick patch
